/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

// AUTOGENERATED. DO NOT EDIT.

export class UrlTestVector {
  constructor(public input: string, public expected: string) {}
}

export class UrlTestVectorOnDemandScheme {
  constructor(
      public input: string, public expected: string, public schemes: string[]) {
  }
}

export const URL_TEST_VECTORS = [
  new UrlTestVector('', ''),
  new UrlTestVector('http://example.com/', 'http://example.com/'),
  new UrlTestVector('https://example.com', 'https://example.com'),
  new UrlTestVector('mailto:foo@example.com', 'mailto:foo@example.com'),
  new UrlTestVector('ftp://example.com', 'ftp://example.com'),
  new UrlTestVector('ftp://username@example.com', 'ftp://username@example.com'),
  new UrlTestVector(
      'ftp://username:password@example.com',
      'ftp://username:password@example.com'),
  new UrlTestVector('HTtp://example.com/', 'HTtp://example.com/'),
  new UrlTestVector(
      'https://example.com/path?foo\u003Dbar#baz',
      'https://example.com/path?foo\u003Dbar#baz'),
  new UrlTestVector(
      'https://example.com:123/path?foo\u003Dbar\u0026abc\u003Ddef#baz',
      'https://example.com:123/path?foo\u003Dbar\u0026abc\u003Ddef#baz'),
  new UrlTestVector('//example.com/path', '//example.com/path'),
  new UrlTestVector('/path', '/path'),
  new UrlTestVector('/path?foo\u003Dbar#baz', '/path?foo\u003Dbar#baz'),
  new UrlTestVector('path', 'path'),
  new UrlTestVector('path?foo\u003Dbar#baz', 'path?foo\u003Dbar#baz'),
  new UrlTestVector('p//ath', 'p//ath'),
  new UrlTestVector('p//ath?foo\u003Dbar#baz', 'p//ath?foo\u003Dbar#baz'),
  new UrlTestVector('#baz', '#baz'),
  new UrlTestVector('?:', '?:'),
  new UrlTestVector(
      'not-data:image/png;base64,z\u003D', 'not-data:image/png;base64,z\u003D'),
  new UrlTestVector(
      'data:image/png;base64,z\u003D', 'data:image/png;base64,z\u003D'),
  new UrlTestVector('tel:+1234567890', 'tel:+1234567890'),
  new UrlTestVector('sms:+1234567890', 'sms:+1234567890'),
  new UrlTestVector('callto:+1234567890', 'callto:+1234567890'),
  new UrlTestVector('wtai://wp/mc;+1234567890', 'wtai://wp/mc;+1234567890'),
  new UrlTestVector('rtsp://example.org/', 'rtsp://example.org/'),
  new UrlTestVector(
      'market://details?id\u003Dapp', 'market://details?id\u003Dapp'),
  new UrlTestVector('itms://itunes.apple.com/us', 'itms://itunes.apple.com/us'),
  new UrlTestVector('javascript:evil(1);', 'about:invalid#zClosurez'),
  new UrlTestVector(
      'javascript:evil(2);//\u000Ahttp://good.com/', 'about:invalid#zClosurez'),
  new UrlTestVector(' javascript:evil(3);', 'about:invalid#zClosurez'),
  new UrlTestVector('\u0009javascript:evil(4);', 'about:invalid#zClosurez'),
  new UrlTestVector('\u000Bjavascript:evil(5);', 'about:invalid#zClosurez'),
  new UrlTestVector('JaVasCriPT:evil(6);', 'about:invalid#zClosurez'),
  new UrlTestVector('javascript:evil(8);', 'about:invalid#zClosurez'),
  new UrlTestVector('javascript:evil(9);', 'about:invalid#zClosurez'),
  new UrlTestVector('javasc\u0009ript:evil(10);', 'about:invalid#zClosurez'),
  new UrlTestVector('javasc\u0009ript:evil(11);', 'about:invalid#zClosurez'),
];

export const URL_TEST_VECTORS_WITH_SCHEME = [];
