/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

// AUTOGENERATED. DO NOT EDIT.

export class UrlTestVector {
  constructor(public input: string, public expected: string) {}
}

export class UrlTestVectorOnDemandScheme {
  constructor(
      public input: string, public expected: string, public schemes: string[]) {
  }
}

export const URL_TEST_VECTORS = [
  new UrlTestVector('', ''),
  new UrlTestVector('http://example.com/', 'http://example.com/'),
  new UrlTestVector('https://example.com', 'https://example.com'),
  new UrlTestVector('mailto:foo@example.com', 'mailto:foo@example.com'),
  new UrlTestVector('ftp://example.com', 'ftp://example.com'),
  new UrlTestVector('ftp://username@example.com', 'ftp://username@example.com'),
  new UrlTestVector(
      'ftp://username:password@example.com',
      'ftp://username:password@example.com'),
  new UrlTestVector('HTtp://example.com/', 'HTtp://example.com/'),
  new UrlTestVector(
      'https://example.com/path?foo\u003Dbar#baz',
      'https://example.com/path?foo\u003Dbar#baz'),
  new UrlTestVector(
      'https://example.com:123/path?foo\u003Dbar\u0026abc\u003Ddef#baz',
      'https://example.com:123/path?foo\u003Dbar\u0026abc\u003Ddef#baz'),
  new UrlTestVector('//example.com/path', '//example.com/path'),
  new UrlTestVector('/path', '/path'),
  new UrlTestVector('/path?foo\u003Dbar#baz', '/path?foo\u003Dbar#baz'),
  new UrlTestVector('path', 'path'),
  new UrlTestVector('path?foo\u003Dbar#baz', 'path?foo\u003Dbar#baz'),
  new UrlTestVector('p//ath', 'p//ath'),
  new UrlTestVector('p//ath?foo\u003Dbar#baz', 'p//ath?foo\u003Dbar#baz'),
  new UrlTestVector('#baz', '#baz'),
  new UrlTestVector('?:', '?:'),
  new UrlTestVector('javascript:evil();', 'about:invalid#zClosurez'),
  new UrlTestVector(
      'javascript:evil();//\u000Ahttp://good.com/', 'about:invalid#zClosurez'),
  new UrlTestVector(
      'not-data:image/png;base64,z\u003D', 'about:invalid#zClosurez'),
  new UrlTestVector('tel:+1234567890', 'about:invalid#zClosurez'),
  new UrlTestVector('sms:+1234567890', 'about:invalid#zClosurez'),
  new UrlTestVector('callto:+1234567890', 'about:invalid#zClosurez'),
  new UrlTestVector('wtai://wp/mc;+1234567890', 'about:invalid#zClosurez'),
  new UrlTestVector('rtsp://example.org/', 'about:invalid#zClosurez'),
  new UrlTestVector('market://details?id\u003Dapp', 'about:invalid#zClosurez'),
  new UrlTestVector('itms://itunes.apple.com/us', 'about:invalid#zClosurez'),
  new UrlTestVector(
      'itms-apps://itunes.apple.com/us', 'about:invalid#zClosurez'),
  new UrlTestVector(
      'itms-appss://itunes.apple.com/us', 'about:invalid#zClosurez'),
  new UrlTestVector(
      'itms-services://?action\u003Ddownload-manifest\u0026url\u003Dfoo',
      'about:invalid#zClosurez'),
  new UrlTestVector('geo:37.7,42.0', 'about:invalid#zClosurez'),
  new UrlTestVector('skype:chat?jid\u003Dfoo', 'about:invalid#zClosurez'),
  new UrlTestVector(
      'whatsapp://send?text\u003DHello', 'about:invalid#zClosurez'),
  new UrlTestVector('ssh://cloud.google.com', 'about:invalid#zClosurez'),
  new UrlTestVector('path\u000A:', 'about:invalid#zClosurez'),
  new UrlTestVector(
      'http://www.f\u0000\u0000.com', 'http://www.f\u0000\u0000.com'),
  new UrlTestVector(
      'data:image/png;base64,abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789+/\u003D',
      'data:image/png;base64,abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789+/\u003D'),
  new UrlTestVector(
      'dATa:iMage/pNg;bASe64,abc\u003D\u003D\u003D',
      'dATa:iMage/pNg;bASe64,abc\u003D\u003D\u003D'),
  new UrlTestVector(
      'data:image/webp;base64,abc\u003D\u003D\u003D',
      'data:image/webp;base64,abc\u003D\u003D\u003D'),
  new UrlTestVector('data:audio/ogg;base64,abc', 'data:audio/ogg;base64,abc'),
  new UrlTestVector('data:audio/midi;base64,abc', 'data:audio/midi;base64,abc'),
  new UrlTestVector('data:audio/mp3;base64,abc', 'data:audio/mp3;base64,abc'),
  new UrlTestVector('data:audio/mp4;base64,abc', 'data:audio/mp4;base64,abc'),
  new UrlTestVector('data:audio/3gpp;base64,abc', 'data:audio/3gpp;base64,abc'),
  new UrlTestVector(
      'data:audio/3gpp2;base64,abc', 'data:audio/3gpp2;base64,abc'),
  new UrlTestVector('data:audio/L16;base64,abc', 'data:audio/L16;base64,abc'),
  new UrlTestVector('data:audio/mpeg;base64,abc', 'data:audio/mpeg;base64,abc'),
  new UrlTestVector('data:audio/oga;base64,abc', 'data:audio/oga;base64,abc'),
  new UrlTestVector('data:audio/opus;base64,abc', 'data:audio/opus;base64,abc'),
  new UrlTestVector('data:audio/wav;base64,abc', 'data:audio/wav;base64,abc'),
  new UrlTestVector(
      'data:audio/x-matroska;base64,z\u003D',
      'data:audio/x-matroska;base64,z\u003D'),
  new UrlTestVector('data:video/mpeg;base64,abc', 'data:video/mpeg;base64,abc'),
  new UrlTestVector(
      'data:video/ogg;base64,z\u003D', 'data:video/ogg;base64,z\u003D'),
  new UrlTestVector(
      'data:video/mp4;base64,z\u003D', 'data:video/mp4;base64,z\u003D'),
  new UrlTestVector(
      'data:video/webm;base64,z\u003D', 'data:video/webm;base64,z\u003D'),
  new UrlTestVector(
      'data:video/x-matroska;base64,z\u003D',
      'data:video/x-matroska;base64,z\u003D'),
  new UrlTestVector(
      'data:video/quicktime;base64,z\u003D',
      'data:video/quicktime;base64,z\u003D'),
  new UrlTestVector(
      'data:video/x-ms-wmv;base64,z\u003D',
      'data:video/x-ms-wmv;base64,z\u003D'),
  new UrlTestVector(
      'data:video/webm;foo\u003Dbar;base64,z\u003D',
      'data:video/webm;foo\u003Dbar;base64,z\u003D'),
  new UrlTestVector(
      'data:video/webm;foo\u003D\"bar\";base64,z\u003D',
      'data:video/webm;foo\u003D\"bar\";base64,z\u003D'),
  new UrlTestVector(
      'data:video/webm;codecs\u003D\"vp8,opus\";base64,z\u003D',
      'data:video/webm;codecs\u003D\"vp8,opus\";base64,z\u003D'),
  new UrlTestVector(
      'data:video/webm;codecs\u003D\"vp8, opus\";base64,z\u003D',
      'data:video/webm;codecs\u003D\"vp8, opus\";base64,z\u003D'),
];

export const URL_TEST_VECTORS_WITH_SCHEME = [
  new UrlTestVectorOnDemandScheme(
      'tEl:+1(23)129-29192A.ABC#;eXt\u003D29',
      'tEl:+1(23)129-29192A.ABC#;eXt\u003D29',
      [
        'TEL',
      ]),
  new UrlTestVectorOnDemandScheme(
      'tEL:123;randmomparam\u003D123', 'tEL:123;randmomparam\u003D123',
      [
        'TEL',
      ]),
  new UrlTestVectorOnDemandScheme(
      ':', 'about:invalid#zClosurez',
      [
        'TEL',
      ]),
  new UrlTestVectorOnDemandScheme(
      'tell:', 'about:invalid#zClosurez',
      [
        'TEL',
      ]),
  new UrlTestVectorOnDemandScheme(
      'not-tel:+1', 'about:invalid#zClosurez',
      [
        'TEL',
      ]),
  new UrlTestVectorOnDemandScheme(
      ' tel:+1', 'about:invalid#zClosurez',
      [
        'TEL',
      ]),
  new UrlTestVectorOnDemandScheme(
      'javascript:evil()', 'about:invalid#zClosurez',
      [
        'TEL',
      ]),
  new UrlTestVectorOnDemandScheme(
      'callto:+1234567890', 'callto:+1234567890',
      [
        'CALLTO',
      ]),
  new UrlTestVectorOnDemandScheme(
      'rtsp://example.org/', 'rtsp://example.org/',
      [
        'RTSP',
      ]),
  new UrlTestVectorOnDemandScheme(
      'intent://scan/#Intent;scheme\u003Dzxing;package\u003Dcom.google.zxing.client.android;end',
      'intent://scan/#Intent;scheme\u003Dzxing;package\u003Dcom.google.zxing.client.android;end',
      [
        'INTENT',
      ]),
  new UrlTestVectorOnDemandScheme(
      'ssh://cloud.google.com', 'ssh://cloud.google.com',
      [
        'SSH',
      ]),
  new UrlTestVectorOnDemandScheme(
      ':', 'about:invalid#zClosurez',
      [
        'SSH',
      ]),
  new UrlTestVectorOnDemandScheme(
      'ssh:cloud.google.com', 'about:invalid#zClosurez',
      [
        'SSH',
      ]),
  new UrlTestVectorOnDemandScheme(
      ' ssh://cloud.google.com', 'about:invalid#zClosurez',
      [
        'SSH',
      ]),
  new UrlTestVectorOnDemandScheme(
      'javascript:evil()', 'about:invalid#zClosurez',
      [
        'SSH',
      ]),
  new UrlTestVectorOnDemandScheme(
      'market://details?id\u003Dapp', 'market://details?id\u003Dapp',
      [
        'MARKET',
      ]),
  new UrlTestVectorOnDemandScheme(
      'itms://itunes.apple.com/us', 'itms://itunes.apple.com/us',
      [
        'ITMS',
      ]),
  new UrlTestVectorOnDemandScheme(
      'itms-appss://itunes.apple.com/us', 'itms-appss://itunes.apple.com/us',
      [
        'ITMS_APPSS',
      ]),
  new UrlTestVectorOnDemandScheme(
      'itms-services://?action\u003Ddownload-manifest\u0026url\u003Dfoo',
      'itms-services://?action\u003Ddownload-manifest\u0026url\u003Dfoo',
      [
        'ITMS_SERVICES',
      ]),
];
